let products=[
    {
        id: 1,
        title: "Javascript",
        location: "Dubai",
        price: 30,
        spaces: 5,
        image: "./images/javascript.jpeg",
        rating: 3,
    },
    {
        id: 2,
        title: "Python",
        location: "Abu Dhabi",
        price: 45,
        spaces: 5,
        image: "./images/python.jpeg",
        rating: 3,
    },
    {
        id: 3,
        title: "HTML",
        location: "Dubai",
        price: 40,
        spaces: 5,
        image: "./images/html.jpeg",
        rating: 4,
    },
    {
        id: 4,
        title: "Django",
        location: "Abu Dhabi",
        price: 33,
        spaces: 5,
        image: "./images/django.jpeg",
        rating: 2,
    },
    {
        id: 5,
        title: "Penetration Testing",
        location: "Dubai",
        price: 90,
        spaces: 5,
        image: "./images/pentest.jpeg",
        rating: 2,
    },
    {
        id: 6,
        title: "Java",
        location: "Abu Dhabi",
        price: 120,
        spaces: 5,
        image: "./images/java.jpeg",
        rating: 4,
    },
    {
        id: 7,
        title: "CCNA",
        location: "Dubai",
        price: 150,
        spaces: 5,
        image: "./images/ccna.jpeg",
        rating: 5,
    },
    {
        id: 8,
        title: "Comptia A+",
        location: "Abu Dhabi",
        price: 170,
        spaces: 5,
        image: "./images/comptia-a+.jpeg",
        rating: 4,
    },
    {
        id: 9,
        title: "SQL",
        location: "Dubai",
        price: 200,
        spaces: 5,
        image: "./images/SQL-server.jpeg",
        rating: 3,
    },
    {
        id: 10,
        title: "Oracle Database",
        location: "Abu Dhabi",
        price: 250,
        spaces: 5,
        image: "./images/oracledb.png",
        rating: 5,
    },
]