let products = [
            {
              "id": 1001,
              "title": "Javascript",
              "description":
                "JavaScript is the world's most popular programming language for web.",
              "price": 20.00,
              "image": "./images/javascript.jpeg",
              "space": 10,
              "rating": 3,
              "location": 3,
            },

            { "id": 1002,
              "title": "Python",
              "description": "Python is an interpreted high-level general-purpose programming language.",
              "price": 30.00,
              "image": "./images/python.png",
              "space": 5,
              "rating": 2,
              "loction": 2,
               },

            { "id": 1003, 
              "title": "HTML",
              "description": "HTML (HyperText Markup Language) is the most basic building block of the Web",
              "price": 11.00,
              "image": "cat-litter.jpeg",
              "space": 15,
              "rating": 4,
              "location": 4,
            },

            { "id": 1004,
              "title": "Django",
              "description": "Django is a Python-based free and open-source web framework that follows the model–template–views architectural pattern.",
              "price": 12.99,
              "image": "./images/django.png",
              "space": 11,
              "rating": 4,
              "location": 4,
            },

            { "id": 1005,
              "title": "Penetration Testing",
              "description": "A penetration test, colloquially known as a pen test or ethical hacking, is an authorized simulated cyberattack on a computer system",
              "price": 49.99,
              "image": "./images/pentest.png",
              "space": 24,
              "rating": 5,
              "rating": 5,
            },

              {
              "id": 1006,
              "title": "Java",
              "description":
                "Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible",
              "price": 20.00,
              "image": "./images/java.jpeg",
              "space": 10,
              "rating": 3,
              "location": 3,
            },

            { "id": 1007,
              "title": "CCNA",
              "description": "CCNA exam covers networking fundamentals, IP services, security fundamentals, automation and programmability",
              "price": 30.00,
              "image": "./images/ccna.jpeg",
              "space": 5,
              "rating": 2,
              "location": 2,
               },


            { "id": 1008, 
              "title": "Comptia A+",
              "description": "A comprehensive step-by-step review for A+ certification, revised for the latest exams",
              "price": 11.00,
              "image": "./images/comptia-a+.png",
              "space": 15,
              "rating": 4,
              "location": 4,
            },

            { "id": 1009,
              "title": "SQL",
              "description": "SQL is a domain-specific language used in programming and designed for managing data held in a relational database management system",
              "price": 12.99,
              "image": "./images/SQL-server.jpeg",
              "space": 11,
              "rating": 4,
              "location": 4,
            },

            { "id": 1010,
              "title": "Oracle Database",
              "description": "Oracle Database is a multi-model database management system produced and marketed by Oracle Corporation.",
              "price": 49.99,
              "image": "./images/oracledb.png",
              "space": 24,
              "rating": 5,
              "location": 5,
            },
          ]